In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('/content/Employee.csv')

In [39]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [40]:
df = df.drop_duplicates()

In [41]:
df = df.dropna()

In [42]:
df.fillna(0, inplace=True)

In [43]:
for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip()
    df[col] = df[col].str.lower()

In [44]:
df.columns = df.columns.str.strip().str.lower()

In [45]:
df

,education,joiningyear,city,paymenttier,age,gender,everbenched,experienceincurrentdomain,leaveornot
0,bachelors,2017,bangalore,3,34,male,no,0,0
1,bachelors,2013,pune,1,28,female,no,3,1
2,bachelors,2014,new delhi,3,38,female,no,2,0
3,masters,2016,bangalore,3,27,male,no,5,1
4,masters,2017,pune,3,24,male,yes,2,1
...,...,...,...,...,...,...,...,...,...
4645,masters,2017,pune,2,31,female,no,2,0
4647,bachelors,2016,pune,3,30,male,no,2,0
4649,masters,2013,pune,2,37,male,no,2,1
4650,masters,2018,new delhi,3,27,male,no,5,1
4651,bachelors,2012,bangalore,3,30,male,yes,2,0

In [46]:
if "age" in df.columns:
    df = df[(df["age"] > 18) & (df["age"] < 60)]

In [47]:
if "gender" in df.columns:
    df["gender"] = df["gender"].replace({
        "m": "male",
        "f": "female"
    })

In [48]:
 df.head()

,education,joiningyear,city,paymenttier,age,gender,everbenched,experienceincurrentdomain,leaveornot
0,bachelors,2017,bangalore,3,34,male,no,0,0
1,bachelors,2013,pune,1,28,female,no,3,1
2,bachelors,2014,new delhi,3,38,female,no,2,0
3,masters,2016,bangalore,3,27,male,no,5,1
4,masters,2017,pune,3,24,male,yes,2,1

In [49]:
df.shape

(2764, 9)